micronaut:
  application:
    name: micronauttest
netty:
  default:
    allocator:
      max-order: 3
endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS # show details for everyone
    url:
      enabled: true
